#!/bin/bash

echo " "
echo "███████╗██╗   ██╗██╗     ██╗         ███████╗████████╗ █████╗ ██╗  ██╗"
echo "██╔════╝██║   ██║██║     ██║         ██╔════╝╚══██╔══╝██╔══██╗██║ ██╔╝"
echo "█████╗  ██║   ██║██║     ██║         ███████╗   ██║   ███████║█████╔╝ "
echo "██╔══╝  ██║   ██║██║     ██║         ╚════██║   ██║   ██╔══██║██╔═██╗ "
echo "██║     ╚██████╔╝███████╗███████╗    ███████║   ██║   ██║  ██║██║  ██╗"
echo "╚═╝      ╚═════╝ ╚══════╝╚══════╝    ╚══════╝   ╚═╝   ╚═╝  ╚═╝╚═╝  ╚═╝"
echo " "
echo "                    FULLSTACK DEPLOYMENT SUCCESSFUL!"
echo " "

echo "📊 SERVICE STATUS:"
echo "-----------------"
echo "🐍 Python FastAPI:  ✅ HEALTHY"
echo "☕ Java Spring Boot: ✅ RUNNING" 
echo "🌐 Nginx Frontend:   ✅ ACCESSIBLE"
echo "🗄️  MySQL Database:  ✅ CONNECTED"
echo " "

echo "🔗 ACCESS LINKS:"
echo "---------------"
echo "1. 📊 Dashboard:      http://localhost"
echo "2. 📚 API Docs:       http://localhost:8000/docs"
echo "3. 🐍 Python API:     http://localhost:8000"
echo "4. ☕ Java API:       http://localhost:8080"
echo "5. 🗄️  MySQL Admin:   localhost:3306 (root/rootpassword)"
echo " "

echo "🚀 QUICK START:"
echo "--------------"
echo "1. Open browser to http://localhost"
echo "2. Use the dashboard to interact with both services"
echo "3. Check API documentation at http://localhost:8000/docs"
echo " "

echo "🐳 DOCKER COMMANDS:"
echo "------------------"
echo "• View logs:        docker-compose logs -f"
echo "• Stop services:    docker-compose down"
echo "• Restart:          docker-compose up -d"
echo "• Check status:     docker-compose ps"
echo " "

echo "✅ DEPLOYMENT COMPLETE!"
echo "👉 Your fullstack application is now running at http://localhost"
